export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const TOGGLE_WATCH_REPO_LABEL = 'TOGGLE_WATCH_REPO_LABEL';
export const GET_ISSUE_LIST = 'GET_ISSUE_LIST';
export const GET_ISSUE_LIST_SUCCESS = 'GET_ISSUE_LIST_SUCCESS';
export const GET_ISSUE_LIST_FAIL = 'GET_ISSUE_LIST_FAIL';
