export default [
  { value: '', text: 'Any Language' },
  { value: 'ActionScript', text: 'ActionScript' },
  { value: 'C', text: 'C' },
  { value: 'C#', text: 'C#' },
  { value: 'C++', text: 'C++' },
  { value: 'Clojure', text: 'Clojure' },
  { value: 'CoffeeScript', text: 'CoffeeScript' },
  { value: 'CSS', text: 'CSS' },
  { value: 'Go', text: 'Go' },
  { value: 'Haskell', text: 'Haskell' },
  { value: 'HTML', text: 'HTML' },
  { value: 'Java', text: 'Java' },
  { value: 'JavaScript', text: 'JavaScript' },
  { value: 'Lua', text: 'Lua' },
  { value: 'Matlab', text: 'Matlab' },
  { value: 'Objective-C', text: 'Objective-C' },
  { value: 'Perl', text: 'Perl' },
  { value: 'PHP', text: 'PHP' },
  { value: 'Python', text: 'Python' },
  { value: 'R', text: 'R' },
  { value: 'Ruby', text: 'Ruby' },
  { value: 'Scala', text: 'Scala' },
  { value: 'Shell', text: 'Shell' },
  { value: 'Swift', text: 'Swift' },
  { value: 'TeX', text: 'TeX' },
  { value: 'Vim script', text: 'Vim script' },
  { value: '1C Enterprise', text: '1C Enterprise' },
  { value: 'ABAP', text: 'ABAP' },
  { value: 'ABNF', text: 'ABNF' },
  { value: 'Ada', text: 'Ada' },
  { value: 'Adobe Font Metrics', text: 'Adobe Font Metrics' },
  { value: 'Agda', text: 'Agda' },
  { value: 'AGS Script', text: 'AGS Script' },
  { value: 'Alloy', text: 'Alloy' },
  { value: 'Alpine Abuild', text: 'Alpine Abuild' },
  { value: 'AMPL', text: 'AMPL' },
  { value: 'AngelScript', text: 'AngelScript' },
  { value: 'Ant Build System', text: 'Ant Build System' },
  { value: 'ANTLR', text: 'ANTLR' },
  { value: 'ApacheConf', text: 'ApacheConf' },
  { value: 'Apex', text: 'Apex' },
  { value: 'API Blueprint', text: 'API Blueprint' },
  { value: 'APL', text: 'APL' },
  { value: 'Apollo Guidance Computer', text: 'Apollo Guidance Computer' },
  { value: 'AppleScript', text: 'AppleScript' },
  { value: 'Arc', text: 'Arc' },
  { value: 'Arduino', text: 'Arduino' },
  { value: 'AsciiDoc', text: 'AsciiDoc' },
  { value: 'ASN.1', text: 'ASN.1' },
  { value: 'ASP', text: 'ASP' },
  { value: 'AspectJ', text: 'AspectJ' },
  { value: 'Assembly', text: 'Assembly' },
  { value: 'ATS', text: 'ATS' },
  { value: 'Augeas', text: 'Augeas' },
  { value: 'AutoHotkey', text: 'AutoHotkey' },
  { value: 'AutoIt', text: 'AutoIt' },
  { value: 'Awk', text: 'Awk' },
  { value: 'Ballerina', text: 'Ballerina' },
  { value: 'Batchfile', text: 'Batchfile' },
  { value: 'Befunge', text: 'Befunge' },
  { value: 'Bison', text: 'Bison' },
  { value: 'BitBake', text: 'BitBake' },
  { value: 'Blade', text: 'Blade' },
  { value: 'BlitzBasic', text: 'BlitzBasic' },
  { value: 'BlitzMax', text: 'BlitzMax' },
  { value: 'Bluespec', text: 'Bluespec' },
  { value: 'Boo', text: 'Boo' },
  { value: 'Brainfuck', text: 'Brainfuck' },
  { value: 'Brightscript', text: 'Brightscript' },
  { value: 'Bro', text: 'Bro' },
  { value: 'C-ObjDump', text: 'C-ObjDump' },
  { value: 'C2hs Haskell', text: 'C2hs Haskell' },
  { value: 'Cap\'n Proto', text: 'Cap\'n Proto' },
  { value: 'CartoCSS', text: 'CartoCSS' },
  { value: 'Ceylon', text: 'Ceylon' },
  { value: 'Chapel', text: 'Chapel' },
  { value: 'Charity', text: 'Charity' },
  { value: 'ChucK', text: 'ChucK' },
  { value: 'Cirru', text: 'Cirru' },
  { value: 'Clarion', text: 'Clarion' },
  { value: 'Clean', text: 'Clean' },
  { value: 'Click', text: 'Click' },
  { value: 'CLIPS', text: 'CLIPS' },
  { value: 'Closure Templates', text: 'Closure Templates' },
  { value: 'CMake', text: 'CMake' },
  { value: 'COBOL', text: 'COBOL' },
  { value: 'ColdFusion', text: 'ColdFusion' },
  { value: 'ColdFusion CFC', text: 'ColdFusion CFC' },
  { value: 'COLLADA', text: 'COLLADA' },
  { value: 'Common Lisp', text: 'Common Lisp' },
  { value: 'Component Pascal', text: 'Component Pascal' },
  { value: 'Cool', text: 'Cool' },
  { value: 'Coq', text: 'Coq' },
  { value: 'Cpp-ObjDump', text: 'Cpp-ObjDump' },
  { value: 'Creole', text: 'Creole' },
  { value: 'Crystal', text: 'Crystal' },
  { value: 'CSON', text: 'CSON' },
  { value: 'Csound', text: 'Csound' },
  { value: 'Csound Document', text: 'Csound Document' },
  { value: 'Csound Score', text: 'Csound Score' },
  { value: 'CSV', text: 'CSV' },
  { value: 'Cuda', text: 'Cuda' },
  { value: 'CWeb', text: 'CWeb' },
  { value: 'Cycript', text: 'Cycript' },
  { value: 'Cython', text: 'Cython' },
  { value: 'D', text: 'D' },
  { value: 'D-ObjDump', text: 'D-ObjDump' },
  { value: 'Darcs Patch', text: 'Darcs Patch' },
  { value: 'Dart', text: 'Dart' },
  { value: 'DataWeave', text: 'DataWeave' },
  { value: 'desktop', text: 'desktop' },
  { value: 'Diff', text: 'Diff' },
  { value: 'DIGITAL Command Language', text: 'DIGITAL Command Language' },
  { value: 'DM', text: 'DM' },
  { value: 'DNS Zone', text: 'DNS Zone' },
  { value: 'Dockerfile', text: 'Dockerfile' },
  { value: 'Dogescript', text: 'Dogescript' },
  { value: 'DTrace', text: 'DTrace' },
  { value: 'Dylan', text: 'Dylan' },
  { value: 'E', text: 'E' },
  { value: 'Eagle', text: 'Eagle' },
  { value: 'Easybuild', text: 'Easybuild' },
  { value: 'EBNF', text: 'EBNF' },
  { value: 'eC', text: 'eC' },
  { value: 'Ecere Projects', text: 'Ecere Projects' },
  { value: 'ECL', text: 'ECL' },
  { value: 'ECLiPSe', text: 'ECLiPSe' },
  { value: 'Edje Data Collection', text: 'Edje Data Collection' },
  { value: 'edn', text: 'edn' },
  { value: 'Eiffel', text: 'Eiffel' },
  { value: 'EJS', text: 'EJS' },
  { value: 'Elixir', text: 'Elixir' },
  { value: 'Elm', text: 'Elm' },
  { value: 'Emacs Lisp', text: 'Emacs Lisp' },
  { value: 'EmberScript', text: 'EmberScript' },
  { value: 'EQ', text: 'EQ' },
  { value: 'Erlang', text: 'Erlang' },
  { value: 'F#', text: 'F#' },
  { value: 'Factor', text: 'Factor' },
  { value: 'Fancy', text: 'Fancy' },
  { value: 'Fantom', text: 'Fantom' },
  { value: 'Filebench WML', text: 'Filebench WML' },
  { value: 'Filterscript', text: 'Filterscript' },
  { value: 'fish', text: 'fish' },
  { value: 'FLUX', text: 'FLUX' },
  { value: 'Formatted', text: 'Formatted' },
  { value: 'Forth', text: 'Forth' },
  { value: 'Fortran', text: 'Fortran' },
  { value: 'FreeMarker', text: 'FreeMarker' },
  { value: 'Frege', text: 'Frege' },
  { value: 'G-code', text: 'G-code' },
  { value: 'Game Maker Language', text: 'Game Maker Language' },
  { value: 'GAMS', text: 'GAMS' },
  { value: 'GAP', text: 'GAP' },
  { value: 'GCC Machine Description', text: 'GCC Machine Description' },
  { value: 'GDB', text: 'GDB' },
  { value: 'GDScript', text: 'GDScript' },
  { value: 'Genie', text: 'Genie' },
  { value: 'Genshi', text: 'Genshi' },
  { value: 'Gentoo Ebuild', text: 'Gentoo Ebuild' },
  { value: 'Gentoo Eclass', text: 'Gentoo Eclass' },
  { value: 'Gerber Image', text: 'Gerber Image' },
  { value: 'Gettext Catalog', text: 'Gettext Catalog' },
  { value: 'Gherkin', text: 'Gherkin' },
  { value: 'GLSL', text: 'GLSL' },
  { value: 'Glyph', text: 'Glyph' },
  { value: 'GN', text: 'GN' },
  { value: 'Gnuplot', text: 'Gnuplot' },
  { value: 'Golo', text: 'Golo' },
  { value: 'Gosu', text: 'Gosu' },
  { value: 'Grace', text: 'Grace' },
  { value: 'Gradle', text: 'Gradle' },
  { value: 'Grammatical Framework', text: 'Grammatical Framework' },
  { value: 'Graph Modeling Language', text: 'Graph Modeling Language' },
  { value: 'GraphQL', text: 'GraphQL' },
  { value: 'Graphviz (DOT)', text: 'Graphviz (DOT)' },
  { value: 'Groovy', text: 'Groovy' },
  { value: 'Groovy Server Pages', text: 'Groovy Server Pages' },
  { value: 'Hack', text: 'Hack' },
  { value: 'Haml', text: 'Haml' },
  { value: 'Handlebars', text: 'Handlebars' },
  { value: 'Harbour', text: 'Harbour' },
  { value: 'Haxe', text: 'Haxe' },
  { value: 'HCL', text: 'HCL' },
  { value: 'HLSL', text: 'HLSL' },
  { value: 'HTML+Django', text: 'HTML+Django' },
  { value: 'HTML+ECR', text: 'HTML+ECR' },
  { value: 'HTML+EEX', text: 'HTML+EEX' },
  { value: 'HTML+ERB', text: 'HTML+ERB' },
  { value: 'HTML+PHP', text: 'HTML+PHP' },
  { value: 'HTTP', text: 'HTTP' },
  { value: 'Hy', text: 'Hy' },
  { value: 'HyPhy', text: 'HyPhy' },
  { value: 'IDL', text: 'IDL' },
  { value: 'Idris', text: 'Idris' },
  { value: 'IGOR Pro', text: 'IGOR Pro' },
  { value: 'Inform 7', text: 'Inform 7' },
  { value: 'INI', text: 'INI' },
  { value: 'Inno Setup', text: 'Inno Setup' },
  { value: 'Io', text: 'Io' },
  { value: 'Ioke', text: 'Ioke' },
  { value: 'IRC log', text: 'IRC log' },
  { value: 'Isabelle', text: 'Isabelle' },
  { value: 'Isabelle ROOT', text: 'Isabelle ROOT' },
  { value: 'J', text: 'J' },
  { value: 'Jasmin', text: 'Jasmin' },
  { value: 'Java Server Pages', text: 'Java Server Pages' },
  { value: 'JFlex', text: 'JFlex' },
  { value: 'Jison', text: 'Jison' },
  { value: 'Jison Lex', text: 'Jison Lex' },
  { value: 'Jolie', text: 'Jolie' },
  { value: 'JSON', text: 'JSON' },
  { value: 'JSON5', text: 'JSON5' },
  { value: 'JSONiq', text: 'JSONiq' },
  { value: 'JSONLD', text: 'JSONLD' },
  { value: 'JSX', text: 'JSX' },
  { value: 'Julia', text: 'Julia' },
  { value: 'Jupyter Notebook', text: 'Jupyter Notebook' },
  { value: 'KiCad Layout', text: 'KiCad Layout' },
  { value: 'KiCad Legacy Layout', text: 'KiCad Legacy Layout' },
  { value: 'KiCad Schematic', text: 'KiCad Schematic' },
  { value: 'Kit', text: 'Kit' },
  { value: 'Kotlin', text: 'Kotlin' },
  { value: 'KRL', text: 'KRL' },
  { value: 'LabVIEW', text: 'LabVIEW' },
  { value: 'Lasso', text: 'Lasso' },
  { value: 'Latte', text: 'Latte' },
  { value: 'Lean', text: 'Lean' },
  { value: 'Less', text: 'Less' },
  { value: 'Lex', text: 'Lex' },
  { value: 'LFE', text: 'LFE' },
  { value: 'LilyPond', text: 'LilyPond' },
  { value: 'Limbo', text: 'Limbo' },
  { value: 'Linker Script', text: 'Linker Script' },
  { value: 'Linux Kernel Module', text: 'Linux Kernel Module' },
  { value: 'Liquid', text: 'Liquid' },
  { value: 'Literate Agda', text: 'Literate Agda' },
  { value: 'Literate CoffeeScript', text: 'Literate CoffeeScript' },
  { value: 'Literate Haskell', text: 'Literate Haskell' },
  { value: 'LiveScript', text: 'LiveScript' },
  { value: 'LLVM', text: 'LLVM' },
  { value: 'Logos', text: 'Logos' },
  { value: 'Logtalk', text: 'Logtalk' },
  { value: 'LOLCODE', text: 'LOLCODE' },
  { value: 'LookML', text: 'LookML' },
  { value: 'LoomScript', text: 'LoomScript' },
  { value: 'LSL', text: 'LSL' },
  { value: 'M', text: 'M' },
  { value: 'M4', text: 'M4' },
  { value: 'M4Sugar', text: 'M4Sugar' },
  { value: 'Makefile', text: 'Makefile' },
  { value: 'Mako', text: 'Mako' },
  { value: 'Markdown', text: 'Markdown' },
  { value: 'Marko', text: 'Marko' },
  { value: 'Mask', text: 'Mask' },
  { value: 'Mathematica', text: 'Mathematica' },
  { value: 'Maven POM', text: 'Maven POM' },
  { value: 'Max', text: 'Max' },
  { value: 'MAXScript', text: 'MAXScript' },
  { value: 'MediaWiki', text: 'MediaWiki' },
  { value: 'Mercury', text: 'Mercury' },
  { value: 'Meson', text: 'Meson' },
  { value: 'Metal', text: 'Metal' },
  { value: 'MiniD', text: 'MiniD' },
  { value: 'Mirah', text: 'Mirah' },
  { value: 'Modelica', text: 'Modelica' },
  { value: 'Modula-2', text: 'Modula-2' },
  { value: 'Module Management System', text: 'Module Management System' },
  { value: 'Monkey', text: 'Monkey' },
  { value: 'Moocode', text: 'Moocode' },
  { value: 'MoonScript', text: 'MoonScript' },
  { value: 'MQL4', text: 'MQL4' },
  { value: 'MQL5', text: 'MQL5' },
  { value: 'MTML', text: 'MTML' },
  { value: 'MUF', text: 'MUF' },
  { value: 'mupad', text: 'mupad' },
  { value: 'Myghty', text: 'Myghty' },
  { value: 'NCL', text: 'NCL' },
  { value: 'Nearley', text: 'Nearley' },
  { value: 'Nemerle', text: 'Nemerle' },
  { value: 'nesC', text: 'nesC' },
  { value: 'NetLinx', text: 'NetLinx' },
  { value: 'NetLinx+ERB', text: 'NetLinx+ERB' },
  { value: 'NetLogo', text: 'NetLogo' },
  { value: 'NewLisp', text: 'NewLisp' },
  { value: 'Nginx', text: 'Nginx' },
  { value: 'Nim', text: 'Nim' },
  { value: 'Ninja', text: 'Ninja' },
  { value: 'Nit', text: 'Nit' },
  { value: 'Nix', text: 'Nix' },
  { value: 'NL', text: 'NL' },
  { value: 'NSIS', text: 'NSIS' },
  { value: 'Nu', text: 'Nu' },
  { value: 'NumPy', text: 'NumPy' },
  { value: 'ObjDump', text: 'ObjDump' },
  { value: 'Objective-C++', text: 'Objective-C++' },
  { value: 'Objective-J', text: 'Objective-J' },
  { value: 'OCaml', text: 'OCaml' },
  { value: 'Omgrofl', text: 'Omgrofl' },
  { value: 'ooc', text: 'ooc' },
  { value: 'Opa', text: 'Opa' },
  { value: 'Opal', text: 'Opal' },
  { value: 'OpenCL', text: 'OpenCL' },
  { value: 'OpenEdge ABL', text: 'OpenEdge ABL' },
  { value: 'OpenRC runscript', text: 'OpenRC runscript' },
  { value: 'OpenSCAD', text: 'OpenSCAD' },
  { value: 'OpenType Feature File', text: 'OpenType Feature File' },
  { value: 'Org', text: 'Org' },
  { value: 'Ox', text: 'Ox' },
  { value: 'Oxygene', text: 'Oxygene' },
  { value: 'Oz', text: 'Oz' },
  { value: 'P4', text: 'P4' },
  { value: 'Pan', text: 'Pan' },
  { value: 'Papyrus', text: 'Papyrus' },
  { value: 'Parrot', text: 'Parrot' },
  { value: 'Parrot Assembly', text: 'Parrot Assembly' },
  { value: 'Parrot Internal Representation', text: 'Parrot Internal Representation' },
  { value: 'Pascal', text: 'Pascal' },
  { value: 'PAWN', text: 'PAWN' },
  { value: 'Pep8', text: 'Pep8' },
  { value: 'Perl 6', text: 'Perl 6' },
  { value: 'Pic', text: 'Pic' },
  { value: 'Pickle', text: 'Pickle' },
  { value: 'PicoLisp', text: 'PicoLisp' },
  { value: 'PigLatin', text: 'PigLatin' },
  { value: 'Pike', text: 'Pike' },
  { value: 'PLpgSQL', text: 'PLpgSQL' },
  { value: 'PLSQL', text: 'PLSQL' },
  { value: 'Pod', text: 'Pod' },
  { value: 'PogoScript', text: 'PogoScript' },
  { value: 'Pony', text: 'Pony' },
  { value: 'PostScript', text: 'PostScript' },
  { value: 'POV-Ray SDL', text: 'POV-Ray SDL' },
  { value: 'PowerBuilder', text: 'PowerBuilder' },
  { value: 'PowerShell', text: 'PowerShell' },
  { value: 'Processing', text: 'Processing' },
  { value: 'Prolog', text: 'Prolog' },
  { value: 'Propeller Spin', text: 'Propeller Spin' },
  { value: 'Protocol Buffer', text: 'Protocol Buffer' },
  { value: 'Public Key', text: 'Public Key' },
  { value: 'Pug', text: 'Pug' },
  { value: 'Puppet', text: 'Puppet' },
  { value: 'Pure Data', text: 'Pure Data' },
  { value: 'PureBasic', text: 'PureBasic' },
  { value: 'PureScript', text: 'PureScript' },
  { value: 'Python console', text: 'Python console' },
  { value: 'Python traceback', text: 'Python traceback' },
  { value: 'QMake', text: 'QMake' },
  { value: 'QML', text: 'QML' },
  { value: 'Racket', text: 'Racket' },
  { value: 'Ragel', text: 'Ragel' },
  { value: 'RAML', text: 'RAML' },
  { value: 'Rascal', text: 'Rascal' },
  { value: 'Raw token data', text: 'Raw token data' },
  { value: 'RDoc', text: 'RDoc' },
  { value: 'REALbasic', text: 'REALbasic' },
  { value: 'Reason', text: 'Reason' },
  { value: 'Rebol', text: 'Rebol' },
  { value: 'Red', text: 'Red' },
  { value: 'Redcode', text: 'Redcode' },
  { value: 'Regular Expression', text: 'Regular Expression' },
  { value: 'Ren\'Py', text: 'Ren\'Py' },
  { value: 'RenderScript', text: 'RenderScript' },
  { value: 'reStructuredText', text: 'reStructuredText' },
  { value: 'REXX', text: 'REXX' },
  { value: 'RHTML', text: 'RHTML' },
  { value: 'Ring', text: 'Ring' },
  { value: 'RMarkdown', text: 'RMarkdown' },
  { value: 'RobotFramework', text: 'RobotFramework' },
  { value: 'Roff', text: 'Roff' },
  { value: 'Rouge', text: 'Rouge' },
  { value: 'RPM Spec', text: 'RPM Spec' },
  { value: 'RUNOFF', text: 'RUNOFF' },
  { value: 'Rust', text: 'Rust' },
  { value: 'Sage', text: 'Sage' },
  { value: 'SaltStack', text: 'SaltStack' },
  { value: 'SAS', text: 'SAS' },
  { value: 'Sass', text: 'Sass' },
  { value: 'Scaml', text: 'Scaml' },
  { value: 'Scheme', text: 'Scheme' },
  { value: 'Scilab', text: 'Scilab' },
  { value: 'SCSS', text: 'SCSS' },
  { value: 'Self', text: 'Self' },
  { value: 'ShaderLab', text: 'ShaderLab' },
  { value: 'ShellSession', text: 'ShellSession' },
  { value: 'Shen', text: 'Shen' },
  { value: 'Slash', text: 'Slash' },
  { value: 'Slim', text: 'Slim' },
  { value: 'Smali', text: 'Smali' },
  { value: 'Smalltalk', text: 'Smalltalk' },
  { value: 'Smarty', text: 'Smarty' },
  { value: 'SMT', text: 'SMT' },
  { value: 'SourcePawn', text: 'SourcePawn' },
  { value: 'SPARQL', text: 'SPARQL' },
  { value: 'Spline Font Database', text: 'Spline Font Database' },
  { value: 'SQF', text: 'SQF' },
  { value: 'SQL', text: 'SQL' },
  { value: 'SQLPL', text: 'SQLPL' },
  { value: 'Squirrel', text: 'Squirrel' },
  { value: 'SRecode Template', text: 'SRecode Template' },
  { value: 'Stan', text: 'Stan' },
  { value: 'Standard ML', text: 'Standard ML' },
  { value: 'Stata', text: 'Stata' },
  { value: 'STON', text: 'STON' },
  { value: 'Stylus', text: 'Stylus' },
  { value: 'Sublime Text Config', text: 'Sublime Text Config' },
  { value: 'SubRip Text', text: 'SubRip Text' },
  { value: 'SuperCollider', text: 'SuperCollider' },
  { value: 'SVG', text: 'SVG' },
  { value: 'SystemVerilog', text: 'SystemVerilog' },
  { value: 'Tcl', text: 'Tcl' },
  { value: 'Tcsh', text: 'Tcsh' },
  { value: 'Tea', text: 'Tea' },
  { value: 'Terra', text: 'Terra' },
  { value: 'Text', text: 'Text' },
  { value: 'Textile', text: 'Textile' },
  { value: 'Thrift', text: 'Thrift' },
  { value: 'TI Program', text: 'TI Program' },
  { value: 'TLA', text: 'TLA' },
  { value: 'TOML', text: 'TOML' },
  { value: 'Turing', text: 'Turing' },
  { value: 'Turtle', text: 'Turtle' },
  { value: 'Twig', text: 'Twig' },
  { value: 'TXL', text: 'TXL' },
  { value: 'Type Language', text: 'Type Language' },
  { value: 'TypeScript', text: 'TypeScript' },
  { value: 'Unified Parallel C', text: 'Unified Parallel C' },
  { value: 'Unity3D Asset', text: 'Unity3D Asset' },
  { value: 'Unix Assembly', text: 'Unix Assembly' },
  { value: 'Uno', text: 'Uno' },
  { value: 'UnrealScript', text: 'UnrealScript' },
  { value: 'UrWeb', text: 'UrWeb' },
  { value: 'Vala', text: 'Vala' },
  { value: 'VCL', text: 'VCL' },
  { value: 'Verilog', text: 'Verilog' },
  { value: 'VHDL', text: 'VHDL' },
  { value: 'Visual Basic', text: 'Visual Basic' },
  { value: 'Volt', text: 'Volt' },
  { value: 'Vue', text: 'Vue' },
  { value: 'Wavefront Material', text: 'Wavefront Material' },
  { value: 'Wavefront Object', text: 'Wavefront Object' },
  { value: 'wdl', text: 'wdl' },
  { value: 'Web Ontology Language', text: 'Web Ontology Language' },
  { value: 'WebAssembly', text: 'WebAssembly' },
  { value: 'WebIDL', text: 'WebIDL' },
  { value: 'wisp', text: 'wisp' },
  { value: 'World of Warcraft Addon Data', text: 'World of Warcraft Addon Data' },
  { value: 'X10', text: 'X10' },
  { value: 'xBase', text: 'xBase' },
  { value: 'XC', text: 'XC' },
  { value: 'XCompose', text: 'XCompose' },
  { value: 'XML', text: 'XML' },
  { value: 'Xojo', text: 'Xojo' },
  { value: 'XPages', text: 'XPages' },
  { value: 'XPM', text: 'XPM' },
  { value: 'XProc', text: 'XProc' },
  { value: 'XQuery', text: 'XQuery' },
  { value: 'XS', text: 'XS' },
  { value: 'XSLT', text: 'XSLT' },
  { value: 'Xtend', text: 'Xtend' },
  { value: 'Yacc', text: 'Yacc' },
  { value: 'YAML', text: 'YAML' },
  { value: 'YANG', text: 'YANG' },
  { value: 'Zephir', text: 'Zephir' },
  { value: 'Zimpl', text: 'Zimpl' },
];
