#import "./RepositoryFragment.gql"

query Viewer { 
  viewer { 
    login
    avatarUrl
    starredRepositories(first: 10) {
      edges {
        cursor
        node {
          ...repo
        }
      }
    }
  }
}