#import "./fragments/RepositoryFragment.gql"
#import "./fragments/LabelFragment.gql"

query Viewer { 
  viewer { 
    login
    avatarUrl
    starredRepositories(first: 10) {
      pageInfo {
        endCursor
        hasNextPage
        hasPreviousPage
        startCursor
      }
      nodes {
        ...repository
        labels(first: 10) {
          pageInfo {
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
          }
          nodes {
            ...label
          }
        }
      }
    }
  }
}