#import "./fragments/RepositoryFragment.gql"
#import "./fragments/IssueFragment.gql"
#import "./fragments/LabelFragment.gql"

query RepositoryIssues ($owner:String!, $name:String!, $labels:[String!]) {
	repository(owner:$owner name:$name) {
    ...repository
		issues(labels:$labels first: 10 states: OPEN orderBy: {field: CREATED_AT direction: DESC}) {
			nodes {
				...issue
				labels(first: 5) {
					nodes {
						...label
					}
				}
			}
		}    
  }
}